### ISSUE TITLE
WalletConfig.arkServerUrl is silently ignored and yields a mainnet wallet against a regtest server

### ISSUE THREAD

**Issue by Kukks** [arkade-os/ts-sdk#869]
`WalletConfig.arkServerUrl` is silently ignored, and the wallet falls back to a **mainnet** provider — including against a regtest server.

## What happens

`ReadonlyWallet.setupWalletConfig` reads only `config.arkProvider`:

```js
const arkProvider = config.arkProvider || new RestArkProvider();
```

`config.arkServerUrl` is never consulted. When it is the only server configuration a caller passes, the wallet is built against `new RestArkProvider()` — whose default is the **mainnet** Arkade server. `indexerProvider` is then derived from that same provider, so the indexer follows it to mainnet too.

Nothing throws, and nothing warns. The network is silently whatever the default provider reports, not the server the caller named.

## Reproduction

`@arkade-os/sdk@0.5.0-rc.4`, against a local regtest arkd whose `/v1/info` correctly reports `"network":"regtest"`:

```js
const w = await Wallet.create({
  identity: SingleKey.fromHex('11'.repeat(32)),
  arkServerUrl: 'http://localhost:7070',
  storage: {
    walletRepository: new InMemoryWalletRepository(),
    contractRepository: new InMemoryContractRepository(),
  },
  settlementConfig: false,
})

console.log(w.network)                     // { bech32: 'bc', hrp: 'ark', name: 'bitcoin' }
console.log(await w.getAddress())          // ark1q...
console.log(await w.getBoardingAddress())  // bc1p...
```

A **mainnet** boarding address, from a wallet the caller asked to build against `http://localhost:7070`.

The server itself is fine — the same process reads it correctly when asked directly:

```js
const p = new RestArkProvider('http://localhost:7070')
;(await p.getInfo()).network            // 'regtest'
getNetwork('regtest')                   // { bech32: 'bcrt', hrp: 'tark', name: 'regtest' }
```

Passing `arkProvider`/`indexerProvider` explicitly produces the correct regtest wallet, so this is specifically the `arkServerUrl` path.

## Why it is worth reporting

`arkServerUrl` is marked `@deprecated` rather than removed, so it still type-checks and still looks like a supported way to name a server. The failure is silent and the wrong direction: a caller pointing at a test server gets a mainnet wallet, mainnet-derived addresses, and a mainnet indexer.

It cost a run of a latency harness before the `bc1p…` prefix gave it away — the addresses are the only symptom, and only if you happen to look at one.

## Suggested handling

Any of these would remove the trap, in rough order of preference:

1. Honour it: `config.arkProvider || (config.arkServerUrl ? new RestArkProvider(config.arkServerUrl) : new RestArkProvider())`, and derive the indexer from the same URL when `indexerUrl` is unset.
2. Throw when `arkServerUrl` is set and `arkProvider` is not, naming the replacement.
3. Remove the field, so the failure is at compile time.

Silently building a mainnet wallet is the one outcome worth avoiding whichever way it goes.

**Comment by Kukks** [comment]
I went to fix this and could not, so here is what I ran instead. Short version: **the symptom is real and reproduces on the 0.5 line through exactly the path you used** — but the cause is not the one named in the report, and that changes what the fix should be.

## What I ran on `master` (0.4.71)

Your repro, verbatim, against a stubbed `/v1/info` reporting `"network":"regtest"`. Not a code read — an actual `Wallet.create` in a vitest run:

```
NETWORK:  {"bech32":"bcrt","pubKeyHash":111,"scriptHash":196,"wif":239,"hrp":"tark","name":"regtest"}
BOARDING: bcrt1phv2xtru50k5s8jeffq9rndsujvhw2vqdygj074gn3d55as6fwvdscunlp8
ORIGINS:  ["http://localhost:7070"]
```

A **regtest** wallet, a `bcrt1p…` boarding address, and every request to the server that was named. `arkServerUrl` is honoured here: `getArkadeServerUrl(config)` at `wallet.ts:196` feeds `new RestArkProvider(arkadeServerUrl)` at `:969`, and the indexer derives from the same URL at `:990` when no custom `arkProvider` is injected. Nothing to fix on this branch.

## What I ran on `feat/v0.5` (0.5.0-rc.4)

Same repro, but written the way an untyped harness writes it — a plain object, no type annotation, which is what a `.mjs` file gets. The stub answers `regtest` for `localhost:7070` and `bitcoin` for anything else, so the output names which server was actually contacted:

```
NETWORK:  {"bech32":"bc","pubKeyHash":0,"scriptHash":5,"wif":128,"hrp":"ark","name":"bitcoin"}
BOARDING: bc1phv2xtru50k5s8jeffq9rndsujvhw2vqdygj074gn3d55as6fwvdszd0kwj
ORIGINS:  ["https://arkade.computer"]
WARNINGS: []
```

**Your report reproduces.** Mainnet wallet, `bc1p…` boarding address, `localhost:7070` never contacted at all, and not one `console.warn`. Same identity as the master run above, so the witness program is identical and only the HRP differs — `bcrt1phv2xtru…` against `bc1phv2xtru…`.

## Where the report and the code disagree

The one thing that does not hold is the stated mechanism:

> `arkServerUrl` is marked `@deprecated` rather than removed, so it still type-checks

On the 0.5 line it *was* removed. `8349a6ae` ("Remove deprecated items", 2026-09-04) dropped it from `BaseWalletConfig`, and that commit is an ancestor of the rc.4 release commit `29d9138e` (2026-09-08) — so it was already gone when rc.4 was cut. Compiling your repro against those types:

```
error TS2353: Object literal may only specify known properties,
and 'arkServerUrl' does not exist in type 'WalletConfig'.
```

So the field is `@deprecated`-but-working on 0.4.x, and removed-and-rejected on 0.5 — for TypeScript callers. The description fits neither branch exactly, which is probably why it read as a deprecation bug.

## What is actually still broken

The type system is not a runtime guard, and the harness that found this was `.mjs`. That is a supported way to use the SDK, not a mistake — which means:

**on the 0.5 line, a JavaScript consumer passing a removed config key gets no signal at all.** The value is silently discarded, the wallet is built against the mainnet default, and the first symptom is an address prefix — if anyone looks. TypeScript users are covered; everyone else gets the failure you hit, and gets it in the wrong direction.

That is your original suggestion 2, narrowed to what is left of the problem:

> Throw when `arkServerUrl` is set and `arkProvider` is not, naming the replacement.

Generalised: validate the config object and reject — or at minimum warn — on keys `WalletConfig` does not recognise, so removing a config option produces a signal in JS and not only in `tsc`. It would also cover `indexerUrl` and `esploraUrl`, which went the same way in the same commit.

There is a real fork in it that is yours to call, not mine: **throw or warn.** Throwing is the honest signal but is a breaking change for any caller currently passing extra properties through a wider object — spread configs, wrappers, anything that forwards. Warning is safe but ignorable. I did not want to pick that on your behalf, so I have not opened a PR.

## Suggestion

I would keep this open rather than close it, re-scoped to the runtime guard — the reported behaviour is real on 0.5 and nothing currently prevents it for JS callers. Happy to send the PR once you say throw or warn, or to file the narrowed issue separately if you would rather this one closed. Your call either way; I have not touched the issue state.

Reproductions above were run against `origin/master` at `5ea42a35` and `origin/feat/v0.5` at `c7ccf2fe`, on Node 24.
